apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ucp-kube-ipsec-workaround
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: ucp-kube-ipsec-workaround
spec:
  selector:
    matchLabels:
      name: ipsec-workaround
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: ipsec-workaround
      labels:
        name: ipsec-workaround
        k8s-app: ucp-kube-ipsec-workaround
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
      - name: ipsec-workaround
        image: ctelfer/ucp-kube-ipsec-workaround
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      terminationGracePeriodSeconds: 10
